app/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include(("bases.urls", "bases"), namespace="bases")),
    path("inv/", include(("inv.urls", "inv"), namespace="inv")),
    path("cmp/", include(("cmp.urls", "cmp"), namespace="cmp")),
    path("admin/", admin.site.urls),
]

app/cmp/urls.py
from django.urls import path, include

from .views import ProveedorView, ProveedorNew, ProveedorEdit, proveedorInactivar


urlpatterns = [
    path("proveedores/", ProveedorView.as_view(), name="proveedor_list"),
    path("proveedores/new", ProveedorNew.as_view(), name="proveedor_new"),
    path("proveedores/edit/<int:pk>", ProveedorEdit.as_view(), name="proveedor_edit"),
    path(
        "proveedores/inactivar/<int:id>", proveedorInactivar, name="proveedor_inactivar"
    ),
]

app/cmp/models.py
from django.db import models
from bases.models import ClaseModelo


# Create your models here.
class Proveedor(ClaseModelo):
    descripcion = models.CharField(max_length=100, unique=True)
    direccion = models.CharField(max_length=250, null=True, blank=True)
    contacto = models.CharField(max_length=100)
    telefono = models.CharField(max_length=10, null=True, blank=True)
    email = models.CharField(max_length=250, null=True, blank=True)

    def __str__(self) -> str:
        return "{}".format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Proveedor, self).save()

    class Meta:
        verbose_name_plural = "Proveedores"

app/cmp/forms.py
from django import forms

from .models import Proveedor


class ProveedorForm(forms.ModelForm):
    email = forms.EmailField(max_length=254)

    class Meta:
        model = Proveedor
        exclude = ["um", "fm", "uc", "fc"]
        widget = {"descripcion": forms.TextInput()}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({"class": "form-control"})

    """
    def clean(self):
        try:
            sc = Proveedor.objects.get(
                descripcion=self.cleaned_data["descripcion"].upper()
            )

            if not self.instance.pk:
                print("Registro ya existe")
                raise forms.ValidationError("Registro Ya Existe")
            elif self.instance.pk != sc.pk:
                print("Cambio no permitido")
                raise forms.ValidationError("Cambio No Permitido")
        except Proveedor.DoesNotExist:
            pass
        return self.cleaned_data
    """

app/cmp/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from cmp.forms import ProveedorForm
from cmp.models import Proveedor
from django.contrib.auth.mixins import LoginRequiredMixin


class ProveedorView(LoginRequiredMixin, generic.ListView):
    model = Proveedor
    template_name = "cmp/proveedor_list.html"
    context_object_name = "obj"
    login_url = "bases:login"


class ProveedorNew(LoginRequiredMixin, generic.CreateView):
    model = Proveedor
    template_name = "cmp/proveedor_form.html"
    context_object_name = "obj"
    form_class = ProveedorForm
    success_url = reverse_lazy("cmp:proveedor_list")
    login_url = "bases:login"

    def form_valid(self, form):
        form.instance.uc = self.request.user
        # print(self.request.user.id)
        return super().form_valid(form)


class ProveedorEdit(LoginRequiredMixin, generic.UpdateView):
    model = Proveedor
    template_name = "cmp/proveedor_form.html"
    context_object_name = "obj"
    form_class = ProveedorForm
    success_url = reverse_lazy("cmp:proveedor_list")
    login_url = "bases:login"

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        print(self.request.user.id)
        return super().form_valid(form)


def proveedorInactivar(request, id):
    template_name = "cmp/inactivar_prv.html"
    contexto = {}
    prv = Proveedor.objects.filter(pk=id).first()

    if not prv:
        return HttpResponse("Proveedor no existe " + str(id))

    if request.method == "GET":
        contexto = {"obj": prv}

    if request.method == "POST":
        prv.estado = False
        prv.save()
        contexto = {"obj": "OK"}
        return HttpResponse("Proveedor Inactivado")

    return render(request, template_name, contexto)

app/cmp/templates/cmp/inactivar_prv.html
<div class="modal-dialog modal-sm">
    <div class="modal-content">
        <form method="POST" class="form-inline">
            {% csrf_token %}
            <div class="col">
                <div class="card border-left-danger shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-warning text-uppercase">
                                    <div class="alert">
                                        ¿ Inactivar <b>{{ obj.descripcion }} </b> ?
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <button type="button" class="btn btn-danger" id="btnInactivar"><i
                                        class="far fa-question-circle"></i>Si, Inactivar</button>
                                <button type="button" class="btn btn-success" onclick="return cerrar_modal()">
                                    No, Cancelar
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<script>
    $(document).ready(function () {
        var token = $('input[name=csrfmiddlewaretoken]').val();
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                    xhr.setRequestHeader("X-CSRFToken", token);
                }
            }
        });
        $("#btnInactivar").click(function (e) {
            e.preventDefault();
            //alert("Probando");

            var id = {{ obj.id }};
            var template = "{% url 'cmp:proveedor_inactivar' obj.id %}";
            //template += id;
            var data = { "id": id };
            data = JSON.stringify(data);
            $.ajax({
                type: "POST",
                url: template,
                data: data,
                beforeSend: function(xhr,settings){
                    $.ajaxSettings.beforeSend(xhr,settings);
                },
                success: function (response) {
                    console.log(response);
                    cerrar_modal();
                    alert(response);
                    //var tipo = (response.startsWith('Proveedor no existe') ? 'red' : 'green');
                    //mensaje(response, tipo);
                },
                error: function (jqXHR, textStatus, errorThrow) {
                    console.log(textStatus, errorThrow);
                    // mensaje(errorThrow, 'red');
                    cerrar_modal();
                }
            });
        });
    });
</script>

app/cmp/templates/cmp/proveedor_form.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        {% if obj %}
        <form role="form" action="{% url 'cmp:proveedor_edit' obj.pk %}" method="post"  class="form-inline">
        {% else %}
        <form role="form" action="{% url 'cmp:proveedor_new' %}" method="post"  class="form-inline">
        {% endif %}
            <div class="col-xl-12 col-md-12 mb-12">
                {% if obj %}
                <div class="card border-left-warning shadow h-100 py-2">
                {% else %}
                <div class="card border-left-success shadow h-100 py-2">
                {% endif %}
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            {% if obj %} Editar {% else %} Nuevo {% endif %} Proveedor
                        </div>
                        <div class="dropdown-divider"></div>
                        {% csrf_token %}
                        <div class="row">
                            {{ form.as_p }}
                        </div>
                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                                <button type="button" class="btn btn-success" onclick="return cerrar_modal()">
                                        Cancelar
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="far fa-calendar-plus fa-2x text-gray-300"></i>
                    </div>
                    </div>
                </div>
                </div>
            </div>
        </form>
    </div>
</div> 

<script>
$(function() {

    /*
    var url = $("form").attr("action");
    var token = jQuery("[name=csrfmiddlewaretoken]").val();

    $("form").submit(function(e){
        e.preventDefault();
        // alert(token);
        var formData = $("form").serializeArray();
        // console.log(formData);
        $.ajax({
            url:url,
            method:"POST",
            headers: {'X-CSRFToken': token },
            data: formData
        })
        .done(function(r,textStatus,xhr){
            if(xhr.status=200){
                location.reload(true);
            }
            else{
                mensaje(textStatus);
            }
        }).fail(function (error) {
                mensaje(error.responseText);
        });
    });*/
});
</script>

app/cmp/templates/cmp/proveedor_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<div class="card shadow mb-4">
  <!-- Card Header - Dropdown -->
  <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
    <h6 class="m-0 font-weight-bold text-primary">Listado de Proveedor</h6>
    <div class="dropdown no-arrow">
      <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
        <div class="dropdown-header">Acciones:</div>
        <a class="dropdown-item" onclick="return abrir_modal('{% url 'cmp:proveedor_new' %}')" href="#"><i class="far fa-calendar-plus"></i> Nuevo</a>
      </div>
    </div>
  </div>
  <!-- Card Body -->
  <div class="card-body">
    {% if not obj %}
    <div class="alert alert-info">No Proveedores</div>
    {% endif %}
    <table class="table table-striped table-hover dt-responsive nowrap" style="width:100%">
      <thead>
        <th>Id</th>        
        <th>Descripcion</th>
        <th>Dirección</th>
        <th>Contacto</th>
        <th>Teléfono</th>
        <th>EMail</th>
        <th>Estado</th>
        <th class="all">Acciones</th>
      </thead>
      <tbody>
        {% for item in obj%}
        <tr>
          <td>{{ item.id }}</td>
          <td>{{ item.descripcion }}</td>
          <td>{{item.direccion}}</td>
          <td>{{ item.contacto }}</td>
          <td>{{ item.telefono }}</td>
          <td>{{ item.email }}</td>
          <td>{{item.estado|yesno:"Activo,Inactivo"}}</td>
          <td>
            <button class="btn btn-warning btn-circle" onclick="return abrir_modal('{% url 'cmp:proveedor_edit' item.id %}')"><i class="far fa-edit"></i></button>
            <button class="btn btn-warning btn-circle" onclick="return abrir_modal('{% url 'cmp:proveedor_inactivar' item.id %}')">
              <i class="far fa-thumbs-down"></i>
            </button>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}
{% block js_page %}
<script>
// Call the dataTables jQuery plugin
$(document).ready(function() {
  $('.table').DataTable();
});
</script>
{% endblock %}